### ISSUE TITLE
Kerning pairs?

### ISSUE THREAD

**Issue by davidmerfield** [davidmerfield/Typeset#11]
Add option to wrap a sequence of characters in a node which could be targeted? This is obviously highly dependent on the typeface e.g. 

```javascript
typeset("Ave, Imperator, morituri te salutant", {kern: ["av", "at"]}) 
```

```css
.kern-av {letter-spacing: 0.95em}
```
