### ISSUE TITLE
Mid-paragraph push/pull spans not working

### ISSUE THREAD

**Issue by davidmerfield** [davidmerfield/Typeset#52]
Hanging punctuation no longer works mid paragraph:

![image](https://user-images.githubusercontent.com/747928/68144938-aed93a00-ff02-11e9-8186-5bef7fbf0f23.png)

Captured on Chrome Version 78.0.3904.70 (Official Build) (64-bit)

Here's the breaking change to fix this courtesy of MB: 

```css
.pull-double, 
.push-double,
.pull-single,
.push-single {
display: inline-block
}
```
